### ISSUE TITLE
Post commit hook

### ISSUE THREAD

**Issue by defnotpaul** [marcolz/my#1]
When does this get shared somewhere?

**Comment by defnotpaul** [comment]
Your response would be appreciated. I really want to see these pictures.

**Comment by defnotpaul** [comment]
@marcolz

**Comment by marcolz** [comment]
![1425518245](https://cloud.githubusercontent.com/assets/20266/14227933/ac5c5f1e-f8bc-11e5-8d4b-82ea25e0ba54.jpg)

**Comment by defnotpaul** [comment]
:+1:

**Comment by marcolz** [comment]
![img_0474](https://cloud.githubusercontent.com/assets/20266/14294751/6828004c-fb27-11e5-8de4-f2700924e813.JPG)

**Comment by maraca** [comment]
Thanks for sharing.

**Comment by maraca** [comment]
++ would look again
